name: vlc-actions-workflow
on: 
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
         id: [21,22,23]
         include:
         - id: 21
           name: EIE3312 Tutorial 4 Fourier Series.mp4
           url: https://s-cloudfront.cdn.ap.panopto.com/sessions/cd1593c5-9eb4-4475-8089-b0bf011f2845/85c94d1a-debc-4c81-bd9e-b0bf011f2858-54072f9c-4850-401f-b08d-b0bf01232190.hls/474764/index.m3u8
         - id: 22
           name: EIE3312 Lecture 12 20231124.mp4
           url: https://s-cloudfront.cdn.ap.panopto.com/sessions/be7cd5e3-c8db-4bdd-b898-b0c400827c77/a087bf7b-5605-4814-a910-b0c400827c7f-f90af942-e640-4bf9-8cc2-b0c40092b952.hls/703855/index.m3u8
         - id: 23
           name: EIE3312 Lecture 13 20231201.mp4
           url: https://s-cloudfront.cdn.ap.panopto.com/sessions/d1754149-409f-4068-b004-b0cb00785f51/a17e36af-085e-479a-9860-b0cb00785f5c-a7c96924-d76b-4716-8cf7-b0cb007b5064.hls/837122/index.m3u8

           
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: curl ffmpeg
        shell: cmd
        run: |
          curl https://mirror-hk.koddos.net/videolan/vlc/3.0.21/win64/vlc-3.0.21-win64.exe -L --output installer.exe &&^
          7z.exe x installer.exe
        
#       - name: download m3u8
#         shell: cmd
#         run: |
#             set PATH=^
#             ${{ github.workspace }}\ffmpeg-6.0-full_build\bin;^
#             %PATH%
#             mkdir downloads &&^
#             ffmpeg -http_persistent 0 -protocol_whitelist file,http,https,tcp,tls,crypto -i "${{ github.workspace }}\input.m3u8" "output.mp4" &&^
#             7z a -tzip -v100m downloads\archive.zip output.mp4 &&^
#             dir

#           -c:v libx264 -c:a aac \

  #  -I dummy
  # :sout=#transcode{vcodec=h264,acodec=mpga,ab=128,channels=2,samplerate=44100,scodec=none} :sout-all :sout-keep
      - shell: cmd
        run: |
          start "" /wait "vlc.exe" --sout=#transcode{vcodec=h264,vb=1500,scale=Auto,acodec=mp3,ab=320,channels=2,samplerate=44100}:std{access=file{no-overwrite},mux=mp4.dst="${{ matrix.name }}"} ${{ matrix.url }} vlc://quit
          
      - shell: cmd
        run: |
          dir
          
      - shell: cmd
        run: |
          7z a -tzip -v100m "downloads/${{ matrix.id }}/${{ matrix.name }}.zip" "${{ matrix.name }}" &&^
          dir
          
      - uses: actions/upload-artifact@v4.6.0
        with:
          name: artifacts-${{ matrix.id }}
          path: "downloads/${{ matrix.id }}/*"
          
#       - name: Release prebuilt
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "downloads/*"
#           allowUpdates: true
#           token: ${{ secrets.GITHUB_TOKEN }}


